### ISSUE TITLE
VS Code should automatically detect EJS template files

### ISSUE THREAD

**Issue by nicolehaugen** [lostintangent/node-e2e-nina2016#20]
This may be a bit outside of the intention of this walkthrough, but something that either we should cover in documentation or try to address with VS Code itself - it involves EJS templates (note that EJS is an option view engine when using the Express generator).

Today, if you are working with EJS as your server side template engine, these html files have an .ejs extension.  As a result, VS Code doesn't recognize by default that this is an html file and then you don't get intellisense when writing html tags.  VS code has a drop-down at the bottom of the window that allows you to switch between treating the file as "Plain Text" to "HTML" - however, I didn't notice this drop-down right away.  Ideally, for a Node.js dev, it would be nice to auto-detect some of these common extensions so that we treat them as HTML by default.

**Comment by lostintangent** [comment]
@nicolehaugen79 This is good feedback, and would be a nice improvement to VS Code itself.

**Comment by nicolehaugen** [comment]
Logged this issue: https://github.com/Microsoft/vscode/issues/22333

**Comment by lostintangent** [comment]
Was this fixed in the nightly release? Your issue was closed as resolve.

**Comment by nicolehaugen** [comment]
Closing - verified this has been fixed in insiders.

**Comment by lostintangent** [comment]
Nice! Thanks for driving this.
