### ISSUE TITLE
A few pain points with the Azure CLI experience

### ISSUE THREAD

**Issue by nicolehaugen** [lostintangent/node-e2e-nina2016#21]
These aren't necessities to fix, but areas that would make the experience smoother and simplified:

1.) The login to Azure from the command line feels slow and clunky:

* When you enter the command "az login" it takes several seconds without any indication that something is happening - at first, I wasn't sure it was working and I cancelled out of the command.  The command should provide some sort of output to indicate that it's doing something.

* After entering the "az login" command, it eventually says "To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code XXXXX to authenticate".  After the user enters this code into the browser, then they can log-in with their azure creds.  This part of the experience could be improved by either allowing the creds to be entered directly in the command line without having the user go to the browser.  Or, at least the browser could be automatically launched and the code already entered for them so that they don't have to do this manually.

2.) Installing the Azure CLI on Windows is a bit complicated.  The good news is that for Macs it's super easy!  It would be nice to try and make the experience simpler for Windows users because today, you have to drill into their install guide and follow multiple steps to install Python in order to use their install scripts for the Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Comment by lostintangent** [comment]
Agreed on both fronts! I'm discussing #2 with the team right now, and we should probably file a suggestion issue for #1.

**Comment by nicolehaugen** [comment]
I logged this issue to track issue #1: https://github.com/Azure/azure-cli/issues/2454

**Comment by lostintangent** [comment]
I'm going to close this, since both issues are being tracked appropriately. The Windows install experience will be resolved soon.
