### ISSUE TITLE
Impact to walk-through from VS Code Insiders bugs

### ISSUE THREAD

**Issue by nicolehaugen** [lostintangent/node-e2e-nina2016#22]
There are a couple of issues that I recently logged against VS Code Insiders that I am tracking here - also, refer to my comments for each one since they impact the walk-through a bit.

1.) [AddConfigurations does not respect `{` on the same line as `[` ](https://github.com/Microsoft/vscode/issues/22624): In the launch.json file, in the "configurations" section if the '[' and '{' appear on the same line, the Node.js configuration snippets fail to display when choosing to add a new debug configuration - this bug has been moved to the VS Code backlog since this formatting shouldn't occur by default.  I ran into this because when I copied and pasted the launch.json file from the walk-through and modified it, I inadvertently changed the default formatting.  Bottom line is that when the user is hand-editing the launch.json file, they should ensure that the formatting is left set to the default where the '[' and '{' appear on separate lines.

2.) [Git clone F1 command error when no folder/project is open](https://github.com/Microsoft/vscode/issues/22620): This appears to be a recent degradation - but, if you're going through the walk-through and you do a git clone with no folder open, you'll hit this.  This will be fixed, but the point here is that the Insiders build is clearly more unstable.  We need to make sure in the walk-through that all the functionality needed is in a stable build and that we don't encourage users to use the Insiders build due to bugs like this one that reflect the churn with the Insiders build.

**Comment by lostintangent** [comment]
@nicolehaugen79 Thanks! Looks like #1 was resolved?

**Comment by nicolehaugen** [comment]
I have verified that issue #1 above has been fixed; looks like #2 has also been fixed, but I'm waiting for that to make it into the insiders build.

Update - verified that #2 has also been fixed.

Leaving this issue open though because we may want to reconsider recommending use of the insiders build for the walkthrough.

**Comment by lostintangent** [comment]
I'm going to close this since I'd still like to recommend using the insiders build. We can re-evaluate this decision as neccessary, but we can open up a new issue at that point.
