### ISSUE TITLE
azure commands arent working as written...

### ISSUE THREAD

**Issue by idkjs** [lostintangent/node-e2e-nina2016#3]
Just found this repo. I had previously posted my issue here: https://github.com/Azure/azure-cli/issues/1682 and on SO.

**Comment by lostintangent** [comment]
@idkjs Could you verify which version of the Azure 2.0 CLI you have installed by running `az --version`? The change from `az resource group` to `az group` happened in `v0.1.0b11`, so if you have an older version installed, you should be able to upgrade (by adding `--upgrade` to the `pip install` command) and be good to go.

Additionally, if you're running into issues using the PIP-based install, the [interactive install script](https://github.com/Azure/azure-cli#interactive-install-script) is the easiest/recommended solution, and may be worth giving a shot.

<img width="179" alt="screen shot 2017-01-08 at 10 36 02 am" src="https://cloud.githubusercontent.com/assets/116461/21752592/401aa692-d590-11e6-9b29-095adf07db5f.png">

**Comment by lostintangent** [comment]
@idkjs I'm closing this since it seems like you got your `az` CLI working via the issue on the `azure-cli` repo. Let me know if that isn't the case and we'll try to figure out the issue. Thanks again!
