### ISSUE TITLE
[PaaS] Getting Started ("Wish List")

### ISSUE THREAD

**Issue by lostintangent** [lostintangent/node-e2e-nina2016#7]
The goal of App Services should be to enable developers to get up and running as quickly as possible, and then ultimately, keep their apps running successfully. This requires optimizing the deployment experience for all meaningful app configurations (e.g. with or without a `package.json`), adhering to community best practices where relevant, and providing the right level of runtime visibility/diagnostics to enable quickly identifying and correcting common issues. We must be deeply motivated to help users fall into the "pit of success", with the goal of increasing the accessibility of Azure, and cloud computing in general. **We want everybody to feel like a pro.**

---

The following illustrates a straw man experience for getting started with Azure App Service, Azure CLI and DocumentDB, with the goal of simplifying the overall E2E for MEAN/MERN-based apps, and reducing the amount of friction and concepts needed to onboard to Azure (e.g. what is an App Service plan?). Much of the work needed to get here is tracked on [GitHub](https://github.com/Azure/azure-cli/issues/created_by/lostintangent) (and discussed further in `Appendix A`), but requires lots of design discussions and clarity.

While the below represents a significant number of improvements as it is, there are many other possibilities to consider, that could continue simplifying and broadening the capabilities of this flow (covered in `Appendix B`).  However, if we could achieve something equivalent to this, that would be a huge step forward.

> In the following examples, stdout is used to illustrate some of the side-effects that each command has, which also helps speak to the enhancements being proposed. The actual text used is by no means meant to be representative of what we might actually display.<br /><br />Additionally, while the below stdout implies that all of this behaior happens transparently (e.g. auto-creating a resource group), it's possible that this should be prompt-driven when args are otherwise omitted. The ultimate intent is to increase the simplicity of commands by reducing the number of concepts to learn, providing smarter defaults across the board, providing a more guided experience, and optimizing the CLI hierarchy to improve efficiency with frequent usage.

## North Star (Local Git-based deployments): 

```
$ az login

  [Info] Launching browser to authenticate...

$ az web create -n todo

  [Info] Resource group created: todo-group
  [Info] App Service Plan created: todo-plan
  [Info] Git remote added: azure
  [Info] Default resource group set: todo-group
  [Info] Default web app set: todo

$ git push azure origin

  [Info] Detected Node.js startup file from package.json: index.js
  [Info] Detected Node.js runtime version from package.json: v6.9.5
  [Info] Acquired your SSL certs via Let's Encrypt

$ az web env update MONGO_URL=$(az docdb create -n todo-data --kind MongoDB --query ".ConnectionString" -otsv)

$ az web browse --logs
 
  [Logs] Application listening on port 3000...
```

## North Star (Remote Git-Based Deployment):

```
$ az login

  [Info] Launching browser to authenticate...

$ az web create -n todo -r lostintangent/node-todo -e MONGO_URL=$(az docdb create -n todo-data --kind MongoDB --query ".ConnectionString" -otsv)

  [Info] Resource group created: todo-group
  [Info] Default resource group set: todo-group
  [Info] App Service Plan created: todo-plan
  [Info] Cloning GitHub repo: lostintangent/node-todo
  [Info] Detected Node.js startup file from package.json: index.js
  [Info] Detected Node.js runtime version from package.json: v6.9.5
  [Info] Acquired your SSL certs via Let's Encrypt
  [Info] Default web app set: todo

$ az web browse --logs
 
  [Logs] Application listening on port 3000...
```

## North Star (Container Deployment): 

```
$ az login

  [Info] Launching browser to authenticate...

$ az web create -n todo -c lostintangent/nod

  [Error] Container "lostintangent/node" is invalid, please try again

$ az web create -n todo -c lostintangent/node

  [Info] Resource group created: todo-group
  [Info] App Service Plan created: todo-plan
  [Info] Pulling lostintangent/node image from DockerHub
  [Info] Default resource group set: todo-group
  [Info] Default web app set: todo

$ az web env update MONGO_URL=$(az docdb create -n todo-data --kind MongoDB --query ".ConnectionString" -otsv)

$ az web browse --logs
 
  [Logs] Application listening on port 3000..
```

## Appendix A: How Do We Get Here?

In order to achieve the above experience, we'd need to make the following improvements to App Service:

1. Establish a rapidly maintained Node.js stack, which includes support for the latest versions as soon as possible.

2. Enhance the Git-based deployment (local and remote) story on Linux to auto-detect the startup file and requested Node.js runtime version. Windows already supports the runtime selection, but it's startup file detection is limited to looking for either `app.js` or `server.js` files, as opposed to inspecting the `package.json` file for an NPM start script or a `main` file.

3. Fix the log tailing support for Linux-based deployments

4. Enable auto-acquisition of SSL certs via Let's Encrypt. This is [already possible](https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/21872#.WJPqzrYrKeg) today, but it's not nearly as simple enough to use. 

5. Update and maintain the Node.js samples that are provided via [Try App Service](http://tryappservice.azure.com), so that we can provide users with a simple/free/modern experience for evaluating App Service for Node.js development.

Additionally, we'd need to make the following improvements to the Azure CLI:

1. Allow auto-creating resource groups and App Service plans if otherwise unspecified

2. Allow setting a default resource group and web app, so that all future commands can omit it

3. Allow enabling Git deployment, or specifying the custom container metadata, as part of the web app creation

4. Allow opening the log stream immediately after launching a web app

5. Validate the custom container metadata on the client-side, in order to prevent failing deployments without any understanding why. The portal does this already, but the CLI doesn't.

6. Allow setting environment variables at the time of web app creation.

7. Provide a simpler way/shortcut for setting environment variables.

8. Renaming the App Service command group to simply "app", and the DocumentDB command group to simply "docdb", in order to improve the ergonomics of using them frequently.

9. Changing the `config appsettings` command group to simply `env` to both shorten the amount of characters needed to type it, but also, to use a term that is more idiomatic with *nix devs.

10. Changing the default web app type to Linux once it GAs, that way, developers will use that platform without needing to worry about it.

11. Lifting the current `az appservice web` command group to simply `az web` to enable improved efficiency when working with web apps.

## Appendix B: Further Opportunities

Beyond the basic "getting started" simplifications, there are numerous other enhancements we could make in order to continue improving and expand the E2E. The following represent examples of potential items to consider as well:

1. Automatic "service binding" between a web app instance and a data store (e.g. DocDB, Redis), which would remove the need to manually retrieve connection strings/credentials, and set the necessary environment variables. Something like the following could be interesting, as a stepping stone towards a full "service broker" like experience.

   ```
   az appservice web binding add -n todo --service todo-mongo --binding MONGO_URL
   ```

2. Ability to provision and manage Application Insights instances, which would mitigate the need to go to the portal in order to setup an APM for your app

3. Ability to easily configure alert and auto-scaling rules based on meaningful metrics (e.g. throughput)

4. Ability to provision an ACR instance as part of creating your web app, if you'd like to use containers, but deployed to a private registry. It's unclear how compelling this would be, but we could definitely simplify the experience if the customer demand was there.

5. While not related to the user experience, we should evaluate whether the App service free tier is sufficient and whether or not DocDB needs a free tier as well, in order to encourage evaluation.

6. Reduce command group depth even further. For example, could we change `az app web` to just `az app`, or would that clash too much with API apps, logic APIs, functions, etc? There's no question that `az app create` flows much nicer than `az app web create`.

**Comment by fiveisprime** [comment]
More detail on this item:

>Establish a rapidly maintained Node.js stack, which includes support for the
>latest versions as soon as possible.

Node versions should be immediately available to users. I know this sounds like a
potential for extra support, but I can assure you that more people will want
immediate access to the latest features (typically JavaScript language features)
than will have issues with changes in new versions.

The node version should also default to the latest LTS version when not provided
in the package.json `engines` field.

The output when deploying needs to be very specific about these two points. I
expect to see something such as

```shell
remote: Package.json found at path: ./package.json
remote: Node.js version 7.4.0 found in ./package.json
remote: No npm version found in ./package.json, defaulting to latest stable version (4.1.2)
remote: Selected node@7.4.0
remote: Selected npm@4.1.2
```

Alternatively when not defined

```shell
remote: Package.json found at path: ./package.json
remote: No Node.js version found in ./package.json, using latest stable version (7.4.0)
remote: No npm version found in ./package.json, using latest stable version (4.1.2)
remote: Selected node@7.4.0
remote: Selected npm@4.1.2
```

Things to note here:

The output of the package.json file is important for users who like to try to use
things like peer dependencies. I'm not sure that's something that is/should be
supported, but that's a different conversation.

The verbosity of these messages helps with explaining to the user what and why so
they can better understand the behavior in the event they need to change
something.

**Comment by lostintangent** [comment]
@fiveisprime Agreed! Should we convert this to a markdown file that we can collaborate on? You could put it wherever is best for you, since I just put it on this repo out of convenience :)

**Comment by fiveisprime** [comment]
Let's leave it here for now, I have some more to add then we can move and share
it. :+1:

**Comment by fiveisprime** [comment]
More detail on this item

>Enhance the Git-based deployment story on Linux to auto-detect the startup file
>and requested Node.js runtime version

**Start scripts need to be honored**

This is the biggest complaint that I have with the platform right now. I can't
do anything other than `$ node file.js`.

## Use case: Express generator

The Express generator's default behavior is the create a shell script to start
the server

```json
"scripts": {
  "start": "node ./bin/www"
}
```

This fails on app services with the error 

```shell
remote: Start script "./bin/www" from package.json not found.
remote: Looking for app.js/server.js under site root.
```

In this case, the root `app.js` is selected, which fails create the http listener
and the app fails in a way that's tough to debug and through no fault of the
user.


## User case: Shorthand scripts

```json
"scripts": {
  "start": "node ."
}
```

```json
"scripts": {
  "start": "node index"
}
```

Both of these translate to `$ node index.js`, but fail with the same error as
above.

**Comment by fiveisprime** [comment]
The goal of app services should be to get and keep apps running.

In general, app services needs to help users recover from common errors. A brand
new Node.js developer should be able to make a few mistakes and still get up and
running - we want everybody to feel like a pro.

This means

- Preventing a poorly formated package.json file from interrupting the deploy if
possible
- Allowing a single .js file to be deployed (no package.json, no dependencies)
- Verbose output indicating that the issue was mitigated

We should adhere to community best practices, but not force them onto the user;
our interest is the users' success.

**Comment by lostintangent** [comment]
@fiveisprime I love this! I just took a stab at adding an intro paragraph with the above sentiment, since I agree that it's helpful to set that tone/intent around the proposal.

**Comment by lostintangent** [comment]
I'm closing this in favor of #19, since the number of title renames here is beginning to annoy me :)
